import {
  reactExtension,
  Select,
  useApplyShippingAddressChange,
  useBuyerJourneyIntercept,
  useSettings,
  useShippingAddress,
} from "@shopify/ui-extensions-react/checkout";
import { useEffect, useState } from "react";

export default reactExtension(
  "purchase.checkout.delivery-address.render-before",
  () => <Extension />
);

function Extension() {
  const address = useShippingAddress();
  const [city, setCity] = useState("");
  const updateShippingAddress = useApplyShippingAddressChange();
  const { pakistan_cities, uk_cities } = useSettings();
  const PAKISTAN_CITIES =
    pakistan_cities ||
    "KARACHI,LAHORE,FAISALABAD,RAWALPINDI,GUJRANWALA,PESHAWAR,MULTAN,HYDERABAD,ISLAMABAD,QUETTA,18 HAZARI,ABBOTABAD,ABDUL HAKIM,ADDA BUN BOSAN,ADDA LAR,ADDA ZAKHEERA,AHMED PUR EAST,AHMED PUR LAMMA,AHMED PUR SIAL,AL AIN,ALI PUR CHATTA,ALIPUR,AMINPUR BANGLOW,ARIF WALA,ATTOCK,AWARAN,BADIN,BAGH,BAHAWALNAGAR,BAHAWALPUR,BANGLOW GOGERA,BANNU,BARA KAHU,BARKHAN,BARNALA,BASIR PUR,BATKHELA,BATTGRAM,BELA,BHAI PHARU,BHAKKAR,BHALWAL,BHAWANA,BHERA,BHIMBER,BHIRIA CITY,BHIRIA ROAD,BHIT SHAH,BUCHIANA MANDI,BUDHLA SANT,BUNAIR,BUREWALA,CHACHRO,CHAK JHUMRA,CHAK SAWARI,CHAKWAL,CHAMAN,CHARSADDA,CHASHMA,CHAWINDA,CHENAB NAGAR,CHICHAWATNI,CHINIOT,CHISHTIAN,CHITRAL,CHOA SYDEN SHAH,CHOR CANTT,CHOWK AZAM,CHOWK SARWER SHAHEED,CHUNIAN,DADU,DAHARKI,DAHRANWALA,DAKOTA,DALBANDIN,DARA ADM KHEL,DARGAI,DARY KHAN,DASKA,DAUD KHEL,DAULATPUR,DEPAL PUR,DERA ALLAHYAR,DERA GHAZI KHAN,DERA ISMAIL KHAN,DERAMURAD JAMAL,DHANOT,DHODHAK,DIGRI,DIJKOT,DINA,DINGA,DOKRI,DOLAT NAGAR,DOUR,DUKKI,DULLE WALA,DUNYA PUR,ELLAH ABAD,FARROQABAD,FATEH JANG,FATEHPUR,FAZIL PUR,FEROZ WATOWAN,FEROZA,FORTE ABBAS,GADOON AMAZAI,GAGGO MANDI,GAMBAT,GARH MOR,GARI KHAIRO,GARI YASIN,GAWADAR,GHAKAR,GHARO,GHAZI ABAD,GHOTKI,GHOUS PUR,GILGIT,GOJRA,GOLARCHI,GUDDU,GUJARKHAN,GUJRAT,HAFIZABAD,HAJIRA,HALA,HANGU,HARIPUR,HARNOULI,HAROONABAD,HASILPUR,HASSAN ABDAL,HATTER,HAVELLIAN,HAZRO,HUB,HUJRA SHAMUQEEM,HUMAK,HUNZA,IQBAL NAGAR,ISKANDARABAD,ISLAMKOT,ISSA KHEL,JABELALI,JACOBABAD,JALAL PUR BHATTIAN,JALALPUR JATTAN,JALALPURPIRWALA,JAMALDIN WALI,JAMPUR,JAMSHORO,JAND WALA,JARANWALA,JARWAR,JATOI,JAWARIAN,JHANG,JHANGIRA,JHANIAN,JHAT PAT,JHELUM,JOUHARABAD,KABIR WALA,KACHA KHO,KAHOTA,KALA BAGH,KALA SHAH KAKU,KALAR KAHAR,KALAT,KALOOR KOT,KAMALIA,KAMER MOSHANI,KAMOKE,KANA NAU,KANDH KOT,KANDIARI,KANDYARO,KARAK,KAROR LALESAN,KAROR PAKKA,KASHMORE,KASOWAL,KASUR,KATLANG,KHAIPUR TAMEWAL,KHAIRPUR NATHAN,KHAIRPUR,KHAN BELA,KHANEWAL,KHANPUR,KHANQA SHARIF,KHAPLU,KHARIAN,KHAZAKHELA,KHEWRA DANDOT,KHIDDER WALA,KHIPRO,KHUSHAB,KHUZDAR,KOHAT,KOT ABDUL MALIK,KOT ADDU,KOT CHUTTA,KOT GHULAM MUHD,KOT MITTHAN,KOT MOMIN,KOT RADHA KISHA,KOT SAMABAH,KOTLA,KOTLI-A.KASHMIR,KOTRI,KUNDIAN,KUNRI,LAKI MARWAT,LALAMUSA,LALIAN,LANDIKOTAL,LARKANA,LAYYAH,LIAQUATPUR,LODHRAN,LORA LAI,LOWER DIR,MACHI GOTH,MAILSI,MAKHDOOM AALI,MALAK WAL,MALAKAND,MAMUN KANJAN,MANDI BAHAUDDIN,MANDI FAIZ ABAD,MANGA MANDI,MANGLA,MANGOWAL,MANKERA,MANSHERA,MARDAN,MASTUNG,MATIARI,MATLI,MEHAR,MEHMOODKOT,MEHRAB PUR,MIAN CHANOO,MIANWALI,MINCHANABAD,MINGORA (SWAT),MIRPUR A.K.,MIRPUR KHAS,MIRPUR MATHELO,MIRPUR SAKRO,MIRWAH GORCHANI,MITHI,MORO,MUBARAK PUR,MUCH,MURID WALA,MURIDKEY,MURREE,MUSLIM BAGH,MUZAFFARABAD AK,MUZAFFARGARH,NANKANA SAHIB,NAROWAL,NARWALA BANGLA,NASIRABAD,NAUABAD,NAUDERO,NAWABSHAH,NEW JATOI,NEW SAEEDABAD,NOORPUR,NOSHERO FEROZ,NOSHKI,NOWSHERA,NOWSHERA VIRKA,NURPUR THAL,OGHI,OKARA,PABBI,PAHAR PUR,PAINSRA,PAK PATTAN SHARIF,PALANDRI,PANJGOOR,PANNU AKIL,PASNI,PASROOR,PATOKI,PETARO,PHALIA,PIND DADAN KHAN,PINDI BHATIAN,PINDI GHEB,PIPLAN,PIRYALO,PISHIN,QABOOLA,QADIRPUR RAWAN,QALANDRABAD,QAZI AHMED,QILA DEDAR SING,QUAIDABAD,RADHAN STATION,RAHIMYARKHAN,RAIWAND,RAJANA,RAJANPUR,RANIPUR,RAS AL KHAIMAH,RATTO DERO,RAWALAKOT,RAWAT,RENALA KHURD,RISALPUR,ROHRI,SADIQABAD,SAHIWAL,SAIDU SHARIF,SAKARDU,SAKRAND,SAMANDRI,SAMARO,SAMBRIAL,SANAWAN,SANGHAR,SANGLA HILL,SARGODAH,SARWAR SHAHEED,SATIANA BANGLA,SEHWAN,SERAI NAURANG,SHABQADAR,SHAHDAD KOT,SHAHDADPUR,SHAHDARA,SHAHKOT,SHAKAR GARH,SHANGLA,SHARAQPUR,SHARJAH,SHEIKHUPURA,SHIKARPUR,SHINKIARI,SHORKOT,SHUJAABAD,SIALKOT,SIBI,SILANWALI,SINJHORO,SITA ROAD,SRAI ALAMGEER,SUI,SUJAWAL,SUKKUR,SUMBRIAL,SUNDAR ADDA,SWABI,SWAT,TAKHAT BAI,TALAGANG,TALL,TANDLIANWALA,TANDO ADAM,TANDO ALLAYAR,TANDO BAGHO,TANDO JAM,TANDO MOHD KHAN,TANK,TARBELA,TAUNSA SHARIF,TAXILA,TEMARGARAH,TERNOL,THARO SHAH,THATTA,THULL,TIBBA SULTAN,TOBATEK-SINGH,TOPI,TURBAT,UBARO,UCH SHARIF,UMERKOT,UMM AL QUWAIN,USTA MOHAMMAD,UPPER DIR,UTHAL,VARI DIR,VEHARI,WAH,WAN BACHRAN,WARAH,WAZIRABAD,WINDER,YAZMAN MANDI,ZAFARWAL,ZAHIRPEER,ZHOB,HAVELI LAKHA,KAMRA,Manawala,Pirmahal,JAFFARABAD,MITHIANI,KHANPUR MAHAR";
  const UK_CITIES =
    uk_cities ||
    "London,Birmingham,Glasgow,Liverpool,Manchester,Sheffield,Leeds,Edinburgh,Bristol,Cardiff";
  const handleSelect = async (value) => {
    try {
      console.log(value, address);
      setCity(value);
      updateShippingAddress({
        address: {
          city: value,
        },
        type: "updateShippingAddress",
      });
    } catch (error) {
      console.log({ error });
    }
  };
  useBuyerJourneyIntercept(
    ({canBlockProgress}) => {
      //console.log("canBlockProgress && city != address.city: ", canBlockProgress && city != address.city)
      return canBlockProgress &&
        city != address.city
        ? {
            behavior: 'block',
            reason: 'Please select city from dropdown',
            errors: [
              {
                message:
                  'Please select city from dropdown',
                // Show an error underneath the city field
                target:
                  '$.cart.deliveryGroups[0].deliveryAddress.city',
              },
              { 
                message: 'Please select city from dropdown',
              }
            ],
          }
        : {
            behavior: 'allow',
          };
    },
  );
  if (address?.countryCode == "PK") {
    return (
      <Select
        label="Select city"
        value={city}
        error={city != address.city ? "Please select city from dropdown" : null}
        onChange={(value) => handleSelect(value)}
        options={PAKISTAN_CITIES?.split(",")?.map((city) => ({
          value: city,
          label: city,
        }))}
      />
    );
  }

  if (address?.countryCode == "GB") {
    return (
      <Select
        label="Select city"
        value={city}
        error={city != address.city ? "Please select city from dropdown" : null}
        onChange={(value) => handleSelect(value)}
        options={UK_CITIES?.split(",")?.map((city) => ({
          value: city,
          label: city,
        }))}
      />
    );
  }
}
